[tool.poetry]
name = "munger"
version = "0.1.0"
description = ""
authors = ["Tom Parker-Shemilt <palfrey@tevp.net>"]

[tool.poetry.dependencies]
python = "^3.7"
watchdog = "^0.9.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
